stages:
  - build

build:
  stage: build
  image: golang:1.11
  before_script:
    # Create a symbolic link under $GOPATH, this is needed for local build
    # i.e. /go/src/gitlab.com/ykyuen/gitlab-ci-go-build
    - cd $GOPATH/src
    - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
    - cd gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME
    - go get github.com/urfave/cli
  script:
    # Compile and name the binary as `hello`
    - go build -o bottalk
    # Execute the binary
    - ./bottalk
